CC     = gcc
CFLAGS = -Wall -lglut -lGL -g
DEPS   = ../lgraph/lgraph.h
LIBS   = -lm
CODE   = main.c graph.c LL.c PQ.c ../lgraph/lgraph.c tree.c

build:
	$(CC) -o run $(DEPS) $(CODE) $(CFLAGS) $(LIBS)

